-- 001_extensions_and_enums.sql
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE user_role        AS ENUM ('EMPLOYEE','HR','ADMIN');
CREATE TYPE user_status      AS ENUM ('PENDING_VERIFICATION','ACTIVE','DISABLED');
CREATE TYPE leave_status     AS ENUM ('PENDING','APPROVED','REJECTED','CANCELLED');
CREATE TYPE step_status      AS ENUM ('PENDING','APPROVED','REJECTED','SKIPPED');
CREATE TYPE ledger_reason    AS ENUM ('OPENING','ACCRUAL','CONSUMED','REVERSAL','CARRY_FORWARD','ADJUSTMENT');
CREATE TYPE punch_direction  AS ENUM ('IN','OUT');
CREATE TYPE day_status       AS ENUM ('PRESENT','ABSENT','HALF_DAY','ON_LEAVE','HOLIDAY','WEEKEND');
CREATE TYPE component_kind   AS ENUM ('EARNING','DEDUCTION');
